/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, деспетчеризацию доставкуов, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using DeliveryApp.Api.Adapters.Http.Contract.src.OpenApi.Attributes;
using DeliveryApp.Api.Adapters.Http.Contract.src.OpenApi.Models;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace DeliveryApp.Api.Adapters.Http.Contract.src.OpenApi.Controllers;

/// <summary>
/// </summary>
[ApiController]
public abstract class DefaultApiController : ControllerBase
{
    /// <summary>
    ///     Создать заказ
    /// </summary>
    /// <remarks>Позволяет создать заказ с целью тестирования</remarks>
    /// <response code="201">Успешный ответ</response>
    /// <response code="0">Ошибка</response>
    [HttpPost]
    [Route("/api/v1/orders")]
    [ValidateModelState]
    [SwaggerOperation("CreateOrder")]
    [SwaggerResponse(0, type: typeof(Error), description: "Ошибка")]
    public abstract Task<IActionResult> CreateOrder();

    /// <summary>
    ///     Получить всех курьеров
    /// </summary>
    /// <remarks>Позволяет получить всех курьеров</remarks>
    /// <response code="200">Успешный ответ</response>
    /// <response code="0">Ошибка</response>
    [HttpGet]
    [Route("/api/v1/couriers/")]
    [ValidateModelState]
    [SwaggerOperation("GetCouriers")]
    [SwaggerResponse(200, type: typeof(List<Courier>), description: "Успешный ответ")]
    [SwaggerResponse(0, type: typeof(Error), description: "Ошибка")]
    public abstract Task<IActionResult> GetCouriers();

    /// <summary>
    ///     Получить все незавершенные заказы
    /// </summary>
    /// <remarks>Позволяет получить все незавершенные</remarks>
    /// <response code="200">Успешный ответ</response>
    /// <response code="0">Ошибка</response>
    [HttpGet]
    [Route("/api/v1/orders/active")]
    [ValidateModelState]
    [SwaggerOperation("GetOrders")]
    [SwaggerResponse(200, type: typeof(List<Order>), description: "Успешный ответ")]
    [SwaggerResponse(0, type: typeof(Error), description: "Ошибка")]
    public abstract Task<IActionResult> GetOrders();
}