name: .NET Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests with coverage
      run: |
        dotnet test --collect:"XPlat Code Coverage" --logger trx
        reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:./CoverageReport -reporttypes:Html